# Docker-compose файл для запуска обоих контейнеров
version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "65432:5432"
    networks:
      backend:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: ap.Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      backend:
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASS: "postgres"
      DB_NAME: "mydb"

networks:
  backend:
    external: true